### ISSUE TITLE
自动模式报错

### ISSUE THREAD

**Issue by ghjcfrt** [CXRunfree/AutoUnipus#1]
自动模式报错，辅助模式正常
自动模式报错为
Traceback (most recent call last):
  File "AutoUnipus.py", line 212, in <module>
  File "AutoUnipus.py", line 139, in auto_func
  File "AutoUnipus.py", line 75, in auto_answer
  File "playwright\sync_api\_generated.py", line 8851, in eval_on_selector
  File "playwright\_impl\_sync_base.py", line 115, in _sync
  File "playwright\_impl\_page.py", line 414, in eval_on_selector
  File "playwright\_impl\_frame.py", line 389, in eval_on_selector
  File "playwright\_impl\_connection.py", line 63, in send
  File "playwright\_impl\_connection.py", line 495, in wrap_api_call
  File "playwright\_impl\_connection.py", line 101, in inner_send
playwright._impl._errors.Error: Failed to find element matching selector ".dialog-header-pc--dialog-header-2qsXD"

**Comment by 2433924494** [comment]
Failed to find element matching selector ".dialog-header-pc--dialog-header-2qsXD"

**Comment by SirTamago** [comment]
我也遇到了自动模式报错，log.txt的内容如下：
```
Traceback (most recent call last):
  File "AutoUnipus.py", line 212, in <module>
  File "AutoUnipus.py", line 143, in auto_func
IndexError: list index out of range
```
